
import AppHeader from "./component/AppHeader";
import Footer from "./component/Footer";
import "./globals.css";


export const metadata = {
  title: "Eloria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title> Dania Rachid </title>
        <meta name="description" content="my portfolio" />
      </head>
      <body
        className={`antialiased`}
      >
        <AppHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
