
import AppHeader from "./component/AppHeader";
import Footer from "./component/Footer";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AppHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
